services:
  reactlessbuster:
    build: ReactlessBuster2/
    container_name: reactlessbuster2
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./ReactlessBuster2/.env
    volumes:
      # データベースの永続化
      - ./ReactlessBuster2/db:/app/db
      # ログの永続化
      - ./ReactlessBuster2/logs:/app/logs
      # 認証情報のマウント
      - ./ReactlessBuster2/credentials:/app/credentials:ro
    # メモリ制限を設定
    mem_limit: 512m
    # CPU制限を設定
    cpus: 0.5
    # ログ設定
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  neoforge-mc:
    image: itzg/minecraft-server
    container_name: neoforge-server
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION: "1.21.8"
      MEMORY: "3G"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped

  minecraft_backuper:
    build: minecraft_backuper/
    container_name: minecraft_backuper
    restart: unless-stopped
    environment:
      - MINECRAFT_DATA_PATH=/app/data
      - BORG_REPO_PATH=/app/repo
      - PYTHONUNBUFFERED=1
      - BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes
    volumes:
      - ./minecraft_backuper:/app
      - ./minecraft-data:/app/data:ro

    # メモリ制限を設定
    mem_limit: 256m
    # CPU制限を設定
    cpus: 0.5
    # ログ設定
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"