# Generated by Django 5.2.7 on 2025-10-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='uuid',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=100),
            preserve_default=False,
        ),
    ]
