# Generated by Django 5.2.7 on 2025-10-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='uuid',
            field=models.CharField(max_length=100),
        ),
    ]
