# Generated by Django 5.2.7 on 2025-10-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participant_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
