# Generated by Django 5.2.7 on 2025-10-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_alter_participant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='uuid',
            field=models.CharField(default='', max_length=36),
        ),
    ]
