# Generated by Django 5.2.7 on 2025-10-12 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_alter_participant_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='game_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
        migrations.CreateModel(
            name='SNSLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sns_links', to='participants.participant')),
            ],
        ),
        migrations.CreateModel(
            name='StreamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_links', to='participants.participant')),
            ],
        ),
    ]
